services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    working_dir: /var/www/html
    command: php-fpm

  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: pastelaria
      POSTGRES_USER: pasteleiro
      POSTGRES_PASSWORD: especial-de-carne
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    working_dir: /var/www/html
    command: ./vendor/bin/phpunit

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
